spring.application.name=api
spring.profiles.active=dev
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jackson.deserialization.fail-on-unknown-properties=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${USUARIO_EMAIL}
spring.mail.password=${EMAIL_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
auth.jwt-secret=${AUTH_JWT_SECRET}
auth.jwt-expiration-miliseg=1200000